### ISSUE TITLE
Handling of elemental compounds

### ISSUE THREAD

**Issue by HaukurPall** [mideind/Greynir#101]
When tokenizing elemental compounds such as "H2O" and "CO2" the tokenizer outputs "H(WORD) 2O(NUMWLETTER)" and "CO(WORD) 2(NUMBER)" when the expected behaviour would be to pass these compounds as-is through the tokenization.

**Comment by vthorsteinsson** [comment]
Should be fixed in version 2.0.0 of Tokenizer (which is now available on GitHub but not on PyPi yet).
