### ISSUE TITLE
Add linter to repo

### ISSUE THREAD

**Issue by hjonasson** [mideind/Greynir#126]
I want to suggest adding a linter to the repo to make coding style easier to enforce on contributors .

**Comment by sveinbjornt** [comment]
We use Black for the Python code, but don't enforce it at the VCS-level. I've been meaning for a while now to set up and configure a good JS linter, anything you recommend? Ideally, one that also inspects the JS code in our Jinja templates...

**Comment by hjonasson** [comment]
I can't pretend to have much experience with different linters. I have only used tslint and eslint myself. Addressing the Jinja templates seems like a worthwhile consideration, I didn't think about it. I will see what I can find.

**Comment by sveinbjornt** [comment]
Our CI via GitHub Actions currently runs jshint on the .js files in static/js/. This will not lint all the JS code in individual Jinja2 templates where a lot of our JS resides, but it's better than nothing. Closing this issue.
