### ISSUE TITLE
Embla getur ekki sótt fréttir.

### ISSUE THREAD

**Issue by userdeadinterface** [mideind/Greynir#204]
Síðan RÚV-Fréttasíðan var uppfærð hefur ekki verið hægt fyrir Emblu að sækja fréttir. Tengillinn "https://ruv.is/json/frettir/hladbord" gefur bara 404-villu og "https://www.ruv.is/json/frettir" sýnir ekkert. Er að láta vita því að þetta hefur ekki verið lagað enn.

**Comment by sveinbjornt** [comment]
Takk fyrir endurgjöfina! Við reddum þessu á nýju ári, @userdeadinterface.

**Comment by sveinbjornt** [comment]
Komið í lag.
